In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split 
from sklearn import svm

In [2]:
df = pd.read_csv('Default_Fin.csv')

In [3]:
df.head()

Index  Employed  Bank Balance  Annual Salary  Defaulted?
0      1         1       8754.36      532339.56           0
1      2         0       9806.16      145273.56           0
2      3         1      12882.60      381205.68           0
3      4         1       6351.00      428453.88           0
4      5         1       9427.92      461562.00           0

In [4]:
df.shape

(10000, 5)

In [5]:
df.isnull().sum()

Index            0
Employed         0
Bank Balance     0
Annual Salary    0
Defaulted?       0
dtype: int64

In [6]:
df.duplicated().sum()

0

In [7]:
df.drop(columns='Index', inplace = True)

In [8]:
X = df.drop(columns='Defaulted?', axis= 1)
y = df['Defaulted?']

In [9]:
print(X)

      Employed  Bank Balance  Annual Salary
0            1       8754.36      532339.56
1            0       9806.16      145273.56
2            1      12882.60      381205.68
3            1       6351.00      428453.88
4            1       9427.92      461562.00
...        ...           ...            ...
9995         1       8538.72      635908.56
9996         1       9095.52      235928.64
9997         1      10144.92      703633.92
9998         1      18828.12      440029.32
9999         0       2411.04      202355.40

[10000 rows x 3 columns]


In [10]:
print(y)

0       0
1       0
2       0
3       0
4       0
       ..
9995    0
9996    0
9997    0
9998    0
9999    0
Name: Defaulted?, Length: 10000, dtype: int64


In [11]:
scaler = StandardScaler()

In [12]:
scaler.fit(X)

StandardScaler()

In [13]:
stander_scaler = scaler.transform(X)

In [14]:
print(stander_scaler)

[[ 0.64593619 -0.21882757  0.81318764]
 [-1.54814054 -0.03761675 -1.60549607]
 [ 0.64593619  0.49241197 -0.13121216]
 ...
 [ 0.64593619  0.02074698  1.8835655 ]
 [ 0.64593619  1.5167441   0.23636282]
 [-1.54814054 -1.31169523 -1.24880518]]


In [15]:
X = stander_scaler
y = df['Defaulted?']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
print(X.shape, X_train.shape, X_test.shape)

(10000, 3) (8000, 3) (2000, 3)


In [18]:
model_1 = LogisticRegression()

In [19]:
model_1.fit(X_train, y_train)

LogisticRegression()

In [20]:
X_train_predict_1 = model_1.predict(X_train)
accuracy_train_predict_1 = accuracy_score(X_train_predict_1, y_train)
X_test_predict_1 = model_1.predict(X_test)
accuracy_test_predict_1 = accuracy_score(X_test_predict_1, y_test)
print ('train: ', accuracy_train_predict_1)
print ('test: ', accuracy_test_predict_1)

train:  0.9745
test:  0.9695


In [21]:
model_2 = svm.SVC(kernel='linear')
model_2.fit(X_train, y_train)

SVC(kernel='linear')

In [22]:
X_train_predict_2 = model_2.predict(X_train)
accuracy_train_predict_2 = accuracy_score(X_train_predict_2, y_train)
X_test_predict_2 = model_2.predict(X_test)
accuracy_test_predict_2 = accuracy_score(X_test_predict_2, y_test)
print ('train: ', accuracy_train_predict_2)
print ('test: ', accuracy_test_predict_2)

train:  0.967
test:  0.9655


In [26]:
input_data = (0,16016.4,295463.52)
id_to_array = np.asarray(input_data)
id_reshaped = id_to_array.reshape(1,-1)
std_data = scaler.transform(id_reshaped)
prediction_output = model_1.predict(std_data)
if(prediction_output[0]==0):
    print("Loan hase not taken.")
else:
    print("Loan hase taken.")

Loan hase not taken.


C:\Users\PMYLS\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [24]:
import pickle
import joblib

In [25]:
with open('model_joblib','wb') as f:
    joblib.dump(model_1,f)